# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#                    __                 ____     __  __  _
#     ________  ____/ /________  ____  / __/__  / /_/ /_(_)
#    / ___/ _ \/ __  / ___/ __ \/ __ \/ /_/ _ \/ __/ __/ /
#   / /  /  __/ /_/ / /__/ /_/ / / / / __/  __/ /_/ /_/ /
#  /_/   \___/\__,_/\___/\____/_/ /_/_/  \___/\__/\__/_/

title: redconfetti
email: jason@redconfetti.com
description: > # this means to ignore newlines until "baseurl:"
  downtempo, triphop, chillout, trance experimentations
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redconfetti.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: redconfetti
github_username: redconfetti

defaults:
  home:
    heading: "music production experiments"
    subheading: "and other musings"

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   image: null             # Image banner source
#   opacity: 1.0            # Banner opacity (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   height: "640px"         # Banner default height
#   min_height: null        # Banner minimum height
#   heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # Custom subheading style (e.g. color: gold)

banner:
  video: null
  image: "https://s3-us-west-1.amazonaws.com/assets.redconfetti.com/images/starry-night-at-a-rest-stop.jpg"
  height: "340px"

# Build settings
theme: jekyll-theme-yat
markdown: kramdown
kramdown:
  input: GFM

logo: https://s3-us-west-1.amazonaws.com/assets.redconfetti.com/images/redconfetti.png
author:
  name: Jason Miller
  picture: https://s3-us-west-1.amazonaws.com/assets.redconfetti.com/images/jason-miller.jpg
  twitter: redconfetti
social:
  name: Jason Miller
  links:
    - https://twitter.com/redconfetti
    - https://www.facebook.com/redconfetti2.0
    - https://github.com/redconfetti
    - https://redconfetti.bandcamp.com/
twitter:
  username: redconfetti
  card: summary

assets:
  url_prefix: "https://s3-us-west-1.amazonaws.com/assets.redconfetti.com"

sitemap: true

yat:
  date_format: "%b %d, %Y"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redconfetti.com" # the base hostname & protocol for your site, e.g. https://example.com
favicon: "https://s3-us-west-1.amazonaws.com/assets.redconfetti.com/images/COMP.GIF" # the favicon for your site

copyright: "© 2005-{currentYear} Jason Miller · All rights reserved"

brand_color: "#DD0000"

utterances:
  repo: "redconfetti/com.redconfetti"
  issue_term: "title"
  label: "utterances comment"
  theme: "github-light"
  follow_site_theme: true

header_pages:
  - index.md
  - about.md
  - music.md
  - other.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _post_archive
  - .gitignore
  - .jekyll-cache/
  - .ruby-version
  - .sass-cache/
  - docker-compose.yml
  - Dockerfile
  - docs
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
